fixtures:
  symlinks:
    "device_manager": "#{source_dir}"
  repositories:
    concat: "git://github.com/puppetlabs/puppetlabs-concat"
    hocon: "git://github.com/puppetlabs/puppetlabs-hocon"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    cron_core: "git://github.com/puppetlabs/puppetlabs-cron_core.git"
    scheduled_task: "git://github.com/puppetlabs/puppetlabs-scheduled_task.git"

