fixtures:
  symlinks:
    "device_manager": "#{source_dir}"
  repositories:
    concat: "git://github.com/puppetlabs/puppetlabs-concat"
    hocon: "git://github.com/puppetlabs/puppetlabs-hocon"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"

